<?php

namespace AppBundle\Repository\Category;

/**
 * CategoryFeildsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryFeildsRepository extends \Doctrine\ORM\EntityRepository
{
}
