<?php

namespace AppBundle\Repository\Category;

/**
 * childCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class childCategoryRepository extends \Doctrine\ORM\EntityRepository {

    public function findByCategoryId($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('c')
                        ->from('AppBundle:Category\childCategory', 'c')
                        ->where("c.category = :id")
                        ->setParameter("id", $id)
                        ->getQuery()
                        ->getResult()
        ;
    }

}
