<?php

namespace AppBundle\Repository\Product;

/**
 * ProductFeildValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFeildValueRepository extends \Doctrine\ORM\EntityRepository
{
}
